"""Monkey-patch ``MCPServerStreamableHTTP`` to follow HTTP redirects.

Why this exists
---------------
``pydantic_ai.mcp.MCPServerStreamableHTTP.client_streams`` builds the internal
``httpx.AsyncClient`` like so (paraphrased)::

    httpx.AsyncClient(
        timeout=httpx.Timeout(self.timeout, read=self.read_timeout),
        headers=self.headers,
    )

Note the missing ``follow_redirects=True``. Several Walmart MCP servers (e.g.
``shelly-mcp-server.prod.walmart.com``) respond with ``307 Temporary Redirect``
on initial handshake (typically to add/strip a trailing slash on the endpoint
path). Without redirect-following the client blows up with::

    httpx.HTTPStatusError: Redirect response 307 Temporary Redirect for url ...

Worse still, some of those redirects downgrade the scheme HTTPS → HTTP
(``shelly`` is a known offender). httpx **strips Authorization headers on
cross-scheme redirects** as a security measure, which then yields::

    {"error": "Missing or invalid Authorization header"}  (HTTP 401)

Fix
---
* ``follow_redirects=True`` so the 307 actually gets followed.
* Use a custom ``httpx.Auth`` flow that re-applies the Authorization header
  on every request — including the redirected one — so the strip is
  harmless. (We only do this for trusted internal Walmart MCP traffic; the
  Authorization header is yanked out of ``self.headers`` and routed through
  the auth flow instead.)

This is intentionally surgical — easy to delete once pydantic-ai ships a
real fix, and limited in scope to the streamable HTTP MCP transport.
"""

from __future__ import annotations

import logging
import os
from contextlib import AsyncExitStack, asynccontextmanager

import httpx

logger = logging.getLogger(__name__)

_PATCH_FLAG = "_walmart_follow_redirects_patched"


class _PreserveAuthHeader(httpx.Auth):
    """httpx auth flow that re-applies the Authorization header on every
    request, including those generated by redirect-following.

    httpx normally strips ``Authorization`` on cross-domain or cross-scheme
    redirects — a sensible default that breaks Walmart's HTTPS→HTTP 307s.
    By wiring auth through the ``Auth`` flow, the header survives.
    """

    requires_request_body = False
    requires_response_body = False

    def __init__(self, header_value: str) -> None:
        self._header_value = header_value

    def auth_flow(self, request):  # type: ignore[override]
        request.headers["Authorization"] = self._header_value
        yield request


def _reexpand_headers(headers):
    """Re-run ``$ENV_VAR`` expansion on a headers mapping.

    Why: ``ManagedMCPServer`` expands env vars **once** at construction time.
    If the user runs ``/marketplace_auth`` mid-session (or the env var was
    missing at startup and seeded later), the cached headers still contain
    the unexpanded ``$PUPPY_MARKETPLACE_TOKEN`` literal. Re-expanding right
    before each connection means the freshest token always wins.
    """
    if not headers:
        return headers
    out = {}
    for k, v in headers.items():
        if isinstance(v, str) and "$" in v:
            out[k] = os.path.expandvars(v)
        else:
            out[k] = v
    return out


def _split_auth_from_headers(headers):
    """Pop ``Authorization`` from a headers mapping (case-insensitively).

    Returns ``(remaining_headers, auth_value_or_None)``.
    """
    if not headers:
        return headers, None
    remaining = {}
    auth_value = None
    for k, v in headers.items():
        if k.lower() == "authorization":
            auth_value = v
        else:
            remaining[k] = v
    return remaining, auth_value


def apply_streamable_http_redirect_patch() -> bool:
    """Apply the monkey-patch. Idempotent. Returns True if patch was applied."""
    try:
        from pydantic_ai.mcp import MCPServerStreamableHTTP
    except Exception as exc:  # noqa: BLE001
        logger.debug("pydantic-ai MCP not importable, skipping redirect patch: %s", exc)
        return False

    if getattr(MCPServerStreamableHTTP, _PATCH_FLAG, False):
        return False  # already patched

    try:
        # NOTE: there are two near-identical names in this module —
        #   * ``streamable_http_client`` (with underscore) takes ``http_client``
        #   * ``streamablehttp_client``  (no  underscore) takes ``httpx_client_factory``
        # Pydantic-ai uses the former. Importing the wrong one breaks everything.
        from mcp.client.streamable_http import (
            streamable_http_client as _streamable_http_client,
        )
    except Exception as exc:  # noqa: BLE001
        logger.debug("Could not import streamable_http_client, skipping patch: %s", exc)
        return False

    @asynccontextmanager
    async def client_streams(self):
        if self.http_client and self.headers:
            raise ValueError("`http_client` is mutually exclusive with `headers`.")

        # Re-expand env vars in headers each time we connect so a fresh
        # token (e.g. just set by /marketplace_auth) actually gets used.
        live_headers = _reexpand_headers(self.headers)

        # Pull Authorization out of plain headers and route it through an
        # httpx Auth flow so it survives cross-scheme redirects (Walmart's
        # gateways love downgrading HTTPS → HTTP, which makes httpx strip
        # any Authorization header carried in plain headers).
        plain_headers, auth_value = _split_auth_from_headers(live_headers)
        auth = _PreserveAuthHeader(auth_value) if auth_value else None

        aexit_stack = AsyncExitStack()
        http_client = self.http_client or await aexit_stack.enter_async_context(
            httpx.AsyncClient(
                timeout=httpx.Timeout(self.timeout, read=self.read_timeout),
                headers=plain_headers,
                follow_redirects=True,  # <-- the whole point of this patch
                auth=auth,
            )
        )
        read_stream, write_stream, *_ = await aexit_stack.enter_async_context(
            _streamable_http_client(self.url, http_client=http_client)
        )
        try:
            yield read_stream, write_stream
        finally:
            await aexit_stack.aclose()

    MCPServerStreamableHTTP.client_streams = client_streams
    setattr(MCPServerStreamableHTTP, _PATCH_FLAG, True)
    logger.info("Patched MCPServerStreamableHTTP.client_streams to follow redirects")
    return True
